export enum MSG {
  USER_NOT_FOUND_BY_ID = 'User not found given by id.',
  PHONE_NUM_ALREADY_USE = 'Phone number already use by another user.',
  ALREADY_WHOLESELLER = 'User already Wholeseller.',
  ACCOUNT_NOT_ACTIVE = 'User account not active',
  INVALID_PASS_PHONE = 'Invalid phone or password',
  ENTER_VALID_PHONE_AND_PASSWORD = 'Please enter a valid phone and password.',
  KYC_NOT_FOUND = 'Kyc not found given by id.',
  KYC_ALREADY_EXIT = 'Kyc abn number already exit.',
  USER_KYC_ALREADY_EXIT = 'User Kyc already created.',
  ADDRESS_NOT_FOUND = 'Address not found given by id.',
  BANNER_NOT_FOUND = 'Banner not found given by id.',
  PRODUCT_NOT_FOUND = 'Product not found given by id.',
  CATEGORY_NOT_FOUND = 'Category not found given by id.',
  CATEGORY_NAME_ALREADY_EXIT = 'Category name already exit.',
  PRODUCT_IMAGE_NOT_FOUND = 'Product Image not found',
}
